[package]
name = "grrs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde_json = "1.0.117"
anyhow = { version = "1.0", default-features = false }
cliclack = "0.3.1"
console = "0.14"